Ajout de la gestion du fontsize
agence-bmobile/quilljs-renderer pull request #7
Opened 2017-05-03 16:24 UTC by julienbmobile

Ajoute la gestion du fontsize dans les formats.

2017-05-09 08:57 UTC, thomas-leroy requested changes

2017-05-09 08:57 UTC, thomas-leroy commented on lib/formats/html.js
> +			console.log(attrs.size)
Nope :panda_face:

2017-05-09 09:07 UTC, julienbmobile commented
@thomas-leroy  fix !

2017-05-11 09:11 UTC, thomas-leroy approved these changes

2017-05-11 09:11 UTC, merged